import type { Post } from "@atelier/core/posts/types";

/**
 * Demo posts served in preview mode (no Supabase). Authors mirror the demo
 * profiles; images are local Bauhaus placeholder SVGs. Display configs
 * deliberately vary to show Phase 3 personalization in the preview feed.
 */

// A 4×3 grey blur placeholder, to exercise the blur-up path in preview.
const DEMO_BLUR =
  "data:image/svg+xml," +
  encodeURIComponent(
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 4 3"><rect width="4" height="3" fill="#c9c5b8"/></svg>',
  );

const RAW: Omit<Post, "subcategory" | "body" | "tags">[] = [
  {
    id: "demo-theo-1",
    author_id: "00000000-0000-4000-a000-000000000002",
    author_handle: "theo",
    author_name: "Theo Brandt",
    author_avatar_url: null,
    checkout_url: null,
    caption: "Chawan #41 — iron glaze, wood-fired. Kept the kiln scar.",
    category: "handmade",
    image_url: "/demo/theo-1.svg",
    image_width: 800,
    image_height: 600,
    original_url: null,
    variants: [{ width: 800, url: "/demo/theo-1.svg" }],
    blur_data: null,
    alt_text: null,
    media_type: "image",
    media_url: null,
    duration_seconds: null,
    display: { frame: "plate", span: "wide", aspect: "natural" },
    created_at: "2026-07-07T09:30:00Z",
  },
  {
    id: "demo-ines-1",
    author_id: "00000000-0000-4000-a000-000000000001",
    author_handle: "ines",
    author_name: "Inês Almeida",
    author_avatar_url: null,
    checkout_url: null,
    caption: "Fira, morning. Silver gelatin, scanned at full resolution.",
    category: "photography",
    image_url: "/demo/ines-1.svg",
    image_width: 800,
    image_height: 600,
    original_url: "/demo/ines-1.svg",
    variants: [
      { width: 480, url: "/demo/ines-1.svg" },
      { width: 800, url: "/demo/ines-1.svg" },
    ],
    blur_data: DEMO_BLUR,
    alt_text:
      "Black-and-white photograph of Fira rooftops at dawn, deep shadows on whitewashed walls",
    media_type: "image",
    media_url: null,
    duration_seconds: null,
    display: { frame: "full-bleed", span: "standard", aspect: "landscape" },
    created_at: "2026-07-06T18:12:00Z",
  },
  {
    id: "demo-ines-2",
    author_id: "00000000-0000-4000-a000-000000000001",
    author_handle: "ines",
    author_name: "Inês Almeida",
    author_avatar_url: null,
    checkout_url: null,
    caption: "Contact sheet — Rossio at noon, frames 12 through 24.",
    category: "photography",
    image_url: "/demo/ines-2.svg",
    image_width: 800,
    image_height: 600,
    original_url: null,
    variants: [{ width: 800, url: "/demo/ines-2.svg" }],
    blur_data: null,
    alt_text: null,
    media_type: "image",
    media_url: null,
    duration_seconds: null,
    display: { frame: "inset", span: "standard", aspect: "square" },
    created_at: "2026-07-03T11:00:00Z",
  },
  {
    id: "demo-theo-2",
    author_id: "00000000-0000-4000-a000-000000000002",
    author_handle: "theo",
    author_name: "Theo Brandt",
    author_avatar_url: null,
    checkout_url: null,
    caption: "Oak stool, wedged joints. No screws, no glue.",
    category: "handmade",
    image_url: "/demo/theo-2.svg",
    image_width: 800,
    image_height: 600,
    original_url: null,
    variants: [{ width: 800, url: "/demo/theo-2.svg" }],
    blur_data: null,
    alt_text: null,
    media_type: "image",
    media_url: null,
    duration_seconds: null,
    display: { frame: "inset", span: "standard", aspect: "natural" },
    created_at: "2026-07-01T15:45:00Z",
  },
  {
    id: "demo-ines-3",
    author_id: "00000000-0000-4000-a000-000000000001",
    author_handle: "ines",
    author_name: "Inês Almeida",
    author_avatar_url: null,
    checkout_url: null,
    caption: "Studies in red — collage from rejected prints.",
    category: "visual",
    image_url: "/demo/ines-3.svg",
    image_width: 800,
    image_height: 600,
    original_url: null,
    variants: [{ width: 800, url: "/demo/ines-3.svg" }],
    blur_data: null,
    alt_text: null,
    media_type: "image",
    media_url: null,
    duration_seconds: null,
    display: {
      frame: "full-bleed",
      span: "full",
      aspect: "landscape",
      school: "constructivism",
    },
    created_at: "2026-06-28T08:20:00Z",
  },
  {
    id: "demo-theo-av1",
    author_id: "00000000-0000-4000-a000-000000000002",
    author_handle: "theo",
    author_name: "Theo Brandt",
    author_avatar_url: null,
    checkout_url: null,
    caption: "Wheel rhythm — three seconds of the studio, looped in my head all week.",
    category: "music",
    image_url: "/demo/theo-1.svg",
    image_width: 800,
    image_height: 600,
    original_url: "/demo/theo-wheel.wav",
    variants: [{ width: 800, url: "/demo/theo-1.svg" }],
    blur_data: null,
    alt_text: "Audio recording; cover shows a blue-and-black circular bowl form",
    media_type: "audio",
    media_url: "/demo/theo-wheel.wav",
    duration_seconds: 3,
    display: { frame: "plate", span: "standard", aspect: "square" },
    created_at: "2026-07-09T08:30:00Z",
  },
  {
    id: "demo-theo-av2",
    author_id: "00000000-0000-4000-a000-000000000002",
    author_handle: "theo",
    author_name: "Theo Brandt",
    author_avatar_url: null,
    checkout_url: null,
    caption: "Trimming chawan #41 — 40 seconds at the wheel. (Preview stub: video file arrives with live storage.)",
    category: "handmade",
    image_url: "/demo/theo-2.svg",
    image_width: 800,
    image_height: 600,
    original_url: null,
    variants: [{ width: 800, url: "/demo/theo-2.svg" }],
    blur_data: null,
    alt_text: "Video; poster shows a stool form in black and yellow",
    media_type: "video",
    media_url: "/demo/theo-trimming.mp4",
    duration_seconds: 40,
    display: { frame: "inset", span: "wide", aspect: "natural" },
    created_at: "2026-07-09T07:15:00Z",
  },
];

// Demo posts predate subcategories/body — default them to null in one place,
// then add one text post (a poem) to exercise the text-post surface.
export const DEMO_POSTS: Post[] = [
  ...RAW.map((p) => ({ ...p, subcategory: null, body: null, tags: [] })),
  {
    id: "demo-text-1",
    tags: ["poetry", "sea"],
    author_id: "00000000-0000-4000-a000-000000000001",
    author_handle: "ines",
    author_name: "Inês Almeida",
    author_avatar_url: null,
    checkout_url: null,
    caption: "Low Tide",
    category: "writing",
    subcategory: "poetry",
    body:
      "The sea unmakes the letters\nI wrote across the sand—\neach wave a gentle censor,\neach retreat a hand\n\nthat gives the beach back blank,\npatient as a page,\nasking only that I kneel\nand write my name again.",
    image_url: "",
    image_width: null,
    image_height: null,
    original_url: null,
    variants: [],
    blur_data: null,
    alt_text: null,
    media_type: "text",
    media_url: null,
    duration_seconds: null,
    display: { frame: "plate", span: "standard", aspect: "natural" },
    created_at: "2026-07-08T10:00:00Z",
  },
];
