/**
 * Localization for the post taxonomy (categories + styles). Lives in core so
 * web and mobile share one source of truth.
 *
 * Design: category names are translated for all 9 locales (the primary, visible
 * axis). Styles translate only the GENERIC recurring terms; proper-noun
 * movements/techniques (Bauhaus, Art Nouveau, Jazz, Haiku, Manga, Bunraku,
 * Chippendale, Repoussé…) are intentionally left canonical — that IS correct
 * localization, you don't translate a proper noun. Anything without an entry
 * falls back to the canonical English label. The map can be extended over time
 * without any code change.
 */

import { categoryCanonicalLabel, styleCanonicalLabel } from "./taxonomy";

export const TAXONOMY_LOCALES = ["en", "fr", "pt", "de", "ja", "zh", "ar", "it", "ru"] as const;
export type TaxonomyLocale = (typeof TAXONOMY_LOCALES)[number];

// ── Category names, by locale → category id → label ─────────────────────
const CATEGORY_I18N: Record<string, Record<string, string>> = {
  fr: { architecture: "Architecture", sculpture: "Sculpture", painting: "Peinture", drawing: "Dessin", illustration: "Illustration", photography: "Photographie", film: "Cinéma", documentary: "Documentaire", music: "Musique", opera: "Opéra", dance: "Danse", ballet: "Ballet", theater: "Théâtre", performance: "Performance", circus: "Cirque", puppetry: "Marionnettes", poetry: "Poésie", prose: "Prose", essay: "Essai", "sequential-art": "Bande dessinée", "video-games": "Jeux vidéo", fashion: "Mode", "product-design": "Design produit", handmade: "Fait main", jewelry: "Bijouterie", furniture: "Mobilier", metalwork: "Ferronnerie", woodworking: "Menuiserie", bookbinding: "Reliure", calligraphy: "Calligraphie", mosaic: "Mosaïque", "stained-glass": "Vitrail" },
  pt: { architecture: "Arquitetura", sculpture: "Escultura", painting: "Pintura", drawing: "Desenho", illustration: "Ilustração", photography: "Fotografia", film: "Cinema", documentary: "Documentário", music: "Música", opera: "Ópera", dance: "Dança", ballet: "Balé", theater: "Teatro", performance: "Performance", circus: "Circo", puppetry: "Teatro de marionetes", poetry: "Poesia", prose: "Prosa", essay: "Ensaio", "sequential-art": "Arte sequencial", "video-games": "Videogames", fashion: "Moda", "product-design": "Design de produto", handmade: "Feito à mão", jewelry: "Joalheria", furniture: "Mobiliário", metalwork: "Trabalho em metal", woodworking: "Marcenaria", bookbinding: "Encadernação", calligraphy: "Caligrafia", mosaic: "Mosaico", "stained-glass": "Vitral" },
  de: { architecture: "Architektur", sculpture: "Skulptur", painting: "Malerei", drawing: "Zeichnung", illustration: "Illustration", photography: "Fotografie", film: "Film", documentary: "Dokumentarfilm", music: "Musik", opera: "Oper", dance: "Tanz", ballet: "Ballett", theater: "Theater", performance: "Performance", circus: "Zirkus", puppetry: "Puppenspiel", poetry: "Poesie", prose: "Prosa", essay: "Essay", "sequential-art": "Comic", "video-games": "Videospiele", fashion: "Mode", "product-design": "Produktdesign", handmade: "Handgemacht", jewelry: "Schmuck", furniture: "Möbel", metalwork: "Metallarbeit", woodworking: "Holzarbeit", bookbinding: "Buchbinderei", calligraphy: "Kalligrafie", mosaic: "Mosaik", "stained-glass": "Glasmalerei" },
  ja: { architecture: "建築", sculpture: "彫刻", painting: "絵画", drawing: "デッサン", illustration: "イラストレーション", photography: "写真", film: "映画", documentary: "ドキュメンタリー", music: "音楽", opera: "オペラ", dance: "ダンス", ballet: "バレエ", theater: "演劇", performance: "パフォーマンス", circus: "サーカス", puppetry: "人形劇", poetry: "詩", prose: "散文", essay: "エッセイ", "sequential-art": "漫画", "video-games": "ビデオゲーム", fashion: "ファッション", "product-design": "プロダクトデザイン", handmade: "ハンドメイド", jewelry: "ジュエリー", furniture: "家具", metalwork: "金工", woodworking: "木工", bookbinding: "製本", calligraphy: "カリグラフィー", mosaic: "モザイク", "stained-glass": "ステンドグラス" },
  zh: { architecture: "建筑", sculpture: "雕塑", painting: "绘画", drawing: "素描", illustration: "插画", photography: "摄影", film: "电影", documentary: "纪录片", music: "音乐", opera: "歌剧", dance: "舞蹈", ballet: "芭蕾", theater: "戏剧", performance: "表演艺术", circus: "马戏", puppetry: "木偶戏", poetry: "诗歌", prose: "散文", essay: "随笔", "sequential-art": "漫画", "video-games": "电子游戏", fashion: "时尚", "product-design": "产品设计", handmade: "手工", jewelry: "珠宝", furniture: "家具", metalwork: "金属工艺", woodworking: "木工", bookbinding: "装帧", calligraphy: "书法", mosaic: "马赛克", "stained-glass": "彩色玻璃" },
  ar: { architecture: "العمارة", sculpture: "النحت", painting: "الرسم", drawing: "الرسم التخطيطي", illustration: "الرسم التوضيحي", photography: "التصوير الفوتوغرافي", film: "السينما", documentary: "الأفلام الوثائقية", music: "الموسيقى", opera: "الأوبرا", dance: "الرقص", ballet: "الباليه", theater: "المسرح", performance: "فنون الأداء", circus: "السيرك", puppetry: "مسرح الدمى", poetry: "الشعر", prose: "النثر", essay: "المقالة", "sequential-art": "القصص المصورة", "video-games": "ألعاب الفيديو", fashion: "الأزياء", "product-design": "تصميم المنتجات", handmade: "صناعة يدوية", jewelry: "المجوهرات", furniture: "الأثاث", metalwork: "أشغال المعادن", woodworking: "النجارة", bookbinding: "تجليد الكتب", calligraphy: "الخط", mosaic: "الفسيفساء", "stained-glass": "الزجاج المعشق" },
  it: { architecture: "Architettura", sculpture: "Scultura", painting: "Pittura", drawing: "Disegno", illustration: "Illustrazione", photography: "Fotografia", film: "Cinema", documentary: "Documentario", music: "Musica", opera: "Opera", dance: "Danza", ballet: "Balletto", theater: "Teatro", performance: "Performance", circus: "Circo", puppetry: "Marionette", poetry: "Poesia", prose: "Prosa", essay: "Saggio", "sequential-art": "Fumetto", "video-games": "Videogiochi", fashion: "Moda", "product-design": "Design di prodotto", handmade: "Fatto a mano", jewelry: "Gioielleria", furniture: "Arredamento", metalwork: "Lavorazione dei metalli", woodworking: "Falegnameria", bookbinding: "Legatoria", calligraphy: "Calligrafia", mosaic: "Mosaico", "stained-glass": "Vetrata" },
  ru: { architecture: "Архитектура", sculpture: "Скульптура", painting: "Живопись", drawing: "Рисунок", illustration: "Иллюстрация", photography: "Фотография", film: "Кино", documentary: "Документальное кино", music: "Музыка", opera: "Опера", dance: "Танец", ballet: "Балет", theater: "Театр", performance: "Перформанс", circus: "Цирк", puppetry: "Кукольный театр", poetry: "Поэзия", prose: "Проза", essay: "Эссе", "sequential-art": "Комиксы", "video-games": "Видеоигры", fashion: "Мода", "product-design": "Дизайн продукта", handmade: "Ручная работа", jewelry: "Ювелирное дело", furniture: "Мебель", metalwork: "Художественная обработка металла", woodworking: "Столярное дело", bookbinding: "Переплётное дело", calligraphy: "Каллиграфия", mosaic: "Мозаика", "stained-glass": "Витраж" },
};

// ── Generic style terms, by locale → style id → label (proper nouns omitted) ──
const STYLE_I18N: Record<string, Record<string, string>> = {
  fr: { classical: "Classique", contemporary: "Contemporain", modern: "Moderne", abstract: "Abstrait", realism: "Réalisme", figurative: "Figuratif", minimalist: "Minimaliste", experimental: "Expérimental", traditional: "Traditionnel", digital: "Numérique", historical: "Historique", nature: "Nature", romantic: "Romantique", narrative: "Narratif", portrait: "Portrait", landscape: "Paysage", drama: "Drame", comedy: "Comédie", geometric: "Géométrique", religious: "Religieux" },
  pt: { classical: "Clássico", contemporary: "Contemporâneo", modern: "Moderno", abstract: "Abstrato", realism: "Realismo", figurative: "Figurativo", minimalist: "Minimalista", experimental: "Experimental", traditional: "Tradicional", digital: "Digital", historical: "Histórico", nature: "Natureza", romantic: "Romântico", narrative: "Narrativo", portrait: "Retrato", landscape: "Paisagem", drama: "Drama", comedy: "Comédia", geometric: "Geométrico", religious: "Religioso" },
  de: { classical: "Klassisch", contemporary: "Zeitgenössisch", modern: "Modern", abstract: "Abstrakt", realism: "Realismus", figurative: "Figurativ", minimalist: "Minimalistisch", experimental: "Experimentell", traditional: "Traditionell", digital: "Digital", historical: "Historisch", nature: "Natur", romantic: "Romantisch", narrative: "Erzählend", portrait: "Porträt", landscape: "Landschaft", drama: "Drama", comedy: "Komödie", geometric: "Geometrisch", religious: "Religiös" },
  ja: { classical: "クラシック", contemporary: "コンテンポラリー", modern: "モダン", abstract: "抽象", realism: "リアリズム", figurative: "具象", minimalist: "ミニマリスト", experimental: "実験的", traditional: "伝統的", digital: "デジタル", historical: "歴史", nature: "自然", romantic: "ロマンティック", narrative: "物語", portrait: "ポートレート", landscape: "風景", drama: "ドラマ", comedy: "コメディ", geometric: "幾何学的", religious: "宗教" },
  zh: { classical: "古典", contemporary: "当代", modern: "现代", abstract: "抽象", realism: "写实", figurative: "具象", minimalist: "极简", experimental: "实验", traditional: "传统", digital: "数字", historical: "历史", nature: "自然", romantic: "浪漫", narrative: "叙事", portrait: "肖像", landscape: "风景", drama: "戏剧", comedy: "喜剧", geometric: "几何", religious: "宗教" },
  ar: { classical: "كلاسيكي", contemporary: "معاصر", modern: "حديث", abstract: "تجريدي", realism: "واقعية", figurative: "تصويري", minimalist: "بسيط", experimental: "تجريبي", traditional: "تقليدي", digital: "رقمي", historical: "تاريخي", nature: "طبيعة", romantic: "رومانسي", narrative: "سردي", portrait: "بورتريه", landscape: "منظر طبيعي", drama: "دراما", comedy: "كوميديا", geometric: "هندسي", religious: "ديني" },
  it: { classical: "Classico", contemporary: "Contemporaneo", modern: "Moderno", abstract: "Astratto", realism: "Realismo", figurative: "Figurativo", minimalist: "Minimalista", experimental: "Sperimentale", traditional: "Tradizionale", digital: "Digitale", historical: "Storico", nature: "Natura", romantic: "Romantico", narrative: "Narrativo", portrait: "Ritratto", landscape: "Paesaggio", drama: "Dramma", comedy: "Commedia", geometric: "Geometrico", religious: "Religioso" },
  ru: { classical: "Классический", contemporary: "Современный", modern: "Модерн", abstract: "Абстрактный", realism: "Реализм", figurative: "Фигуративный", minimalist: "Минималистичный", experimental: "Экспериментальный", traditional: "Традиционный", digital: "Цифровой", historical: "Исторический", nature: "Природа", romantic: "Романтический", narrative: "Нарративный", portrait: "Портрет", landscape: "Пейзаж", drama: "Драма", comedy: "Комедия", geometric: "Геометрический", religious: "Религиозный" },
};

/** Localized category label; falls back to the canonical English name. */
export function localizedCategoryLabel(id: string, locale: string): string {
  return CATEGORY_I18N[locale]?.[id] ?? categoryCanonicalLabel(id);
}

/** Localized style label; falls back to the canonical label (proper nouns stay canonical). */
export function localizedStyleLabel(catId: string, styleId: string, locale: string): string {
  return STYLE_I18N[locale]?.[styleId] ?? styleCanonicalLabel(catId, styleId);
}
