// ffprobe every narration clip and (re)write src/durations.ts with the real
// per-language timings. Run after gen-vo.ts:  bun measure-durations.ts
import { writeFileSync } from "node:fs";
import { LOCALES, VO_FILES } from "./src/strings";

const probe = (path: string): number => {
  const p = Bun.spawnSync([
    "ffprobe", "-v", "error", "-show_entries", "format=duration",
    "-of", "default=noprint_wrappers=1:nokey=1", path,
  ]);
  return parseFloat(p.stdout.toString().trim()) || 0;
};

const out: Record<string, Record<string, number>> = {};
for (const l of LOCALES) {
  out[l] = {};
  for (const f of VO_FILES) {
    const d = probe(`public/audio/vo/${l}/${f}.mp3`);
    out[l][f] = d || out.en?.[f] || 5; // missing clip → fall back to en, then 5s
  }
}

writeFileSync(
  "src/durations.ts",
  `// Auto-generated by measure-durations.ts — per-language narration durations (seconds).
import type { Locale } from "./strings";

export const DURATIONS: Record<Locale, Record<string, number>> = ${JSON.stringify(out, null, 2)};
`,
);
console.log("wrote src/durations.ts");
